### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by echen831** [echen831/Robbyhood#1]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
Hey Eric, good job! Here are my comments:

1. Try to match the styling of Robinhood closer on the session form. Center the form vertically on the page. Make the input boxes a little lighter and maybe get rid of the default border they have, only adding one on hover/focus. The input boxes and buttons should not change size when hovered over (you probably need to set `box-sizing: border-box` in your CSS reset file). Add `cursor: pointer` to the buttons as well. Render the error messages below the input boxes so it doesn't cause things to move around on the page, and make them a bolder font.
![Screen Shot 2020-04-30 at 3 56 29 PM](https://user-images.githubusercontent.com/32026924/80767634-30e69c00-8afd-11ea-8754-ee452f8a4c96.png)
![Screen Shot 2020-04-30 at 3 56 36 PM](https://user-images.githubusercontent.com/32026924/80767635-317f3280-8afd-11ea-8f45-062ab3e8288f.png)

2. Right now pressing enter on the form submits with the 'Demo User' data, even if I'm on the sign up form which doesn't have a demo user button.
3.  Remove your Redux logger/console logs from production
